service: api-name
provider:
    name: aws
    runtime: nodejs8.10
    memorySize: 128
    timeout: 5
    stage: pro
    region: us-east-1
functions:
    users:
        handler: functions/users.handler
        events:
            - http:
                path: /users
                method: get
                cors: true
            - http:
                path: /users/{id}
                method: get
                cors: true
            - http:
                path: /users
                method: post
                cors: true
            - http:
                path: /users
                method: put
                cors: true
            - http:
                path: /users
                method: delete
                cors: true
    worker:
        handler: workers/example.handler
        events:
        - schedule: 
                rate: rate(1 minute)
  
plugins:
    - serverless-offline
    - serverless-offline-scheduler